dbt_project:
  outputs:
    dev:
      dataset: transformed_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/service_accounts/key.json # Update this field with your file name, example: /opt/airflow/service_accounts/airflow-***116-83db69931a10.json
      # keyfile: key.json
      location: asia-southeast2 # Update this field with your dataset location, example: US
      method: service-account
      priority: interactive
      project: belajar-data-maswin # Update this field with your BigQuery project ID
      threads: 1
      type: bigquery
  target: dev

  